### ISSUE TITLE
Checkout of mmpose not reproducible

### ISSUE THREAD

**Issue by kowale** [rccchoudhury/tempo#1]
Hi, thanks for sharing the code! I've been trying to reproduce your paper, but having troubles with

```
git checkout cc87e7ec
```

from `setup.sh`. It throws

```
error: pathspec 'cc87e7ec' did not match any file(s) known to git
```

Perhaps it's a typo? Do you remember the release tag or any details that could help?

Thanks!

**Comment by rccchoudhury** [comment]
Hi, it should be fixed now. Sorry about that!

**Comment by kowale** [comment]
Thanks! I don't see any new commits/branches here nor in mmpose, still getting the same error. Maybe the fix didn't push correctly?

**Comment by rccchoudhury** [comment]
Oops, sorry about that. It should show up now.
